/**
 *  PROBLEM 12
 *  The sequence of triangle numbers is generated by adding the natural numbers. 
 *  So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *  1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *  
 *  28 is the first triangle number to have over five divisors. (1,2,4,7,14,28)
 *  What is the value of the first triangle number to have over five hundred divisors?
 */
// import {BigNumber} from 'bignumber.js'

function solution(){
    
    const divisors = (n) => {
        let arr = [1, n];
        let q = Math.floor(Math.sqrt(n));
        for (let i = 2; i < q; i++){
            if (n%i == 0){
                arr.push(i);
                arr.push(n/i);
            }
        }
        return arr.length;
    };
    let divs = 1;
    let i = 1;

    while (divs < 500){
        i++;
        let u = (i + i%2)/2;
        let v = (i + ((i + 1)%2));
        var n = u * v;
        divs = divisors(n);
    }
    return n;
}

//INPUT GOES HERE
let q = [0];

//TIME STUFF
let times = [];
let solutions = [];
for (let i = 0; i < 5; i++){
    let hrStart = process.hrtime();
    let g = solution(...q);
    let hrEnd = process.hrtime(hrStart);
    times.push(hrEnd);
    solutions.push(g);
}
let tot = [0, 0];
for (let i in times){
    tot[0] += times[i][0];
    tot[1] += times[i][1];
}
tot[0] /= 5;
tot[1] /= 5;
let g = solutions[0];

console.log(`Answer: ${g} Execution Time: ${tot[0]}s, ${tot[1]/1000000}ms`);

/**
 *      SUBMITTED ON        2018/11/15
 *                          CORRECT
 *      VALUE:              76576500
 *      RUNTIME:            385.552ms
 */

  /**
  *     UPDATED ON          2018/11/19
  *     VALUE:              76576500
  *     RUNTIME:            317.712ms
  */